### PR TITLE
[Feat][Homepage] Stats Counter

### PR DESCRIPTION
**Pull request by houzyk**
Added a stats counter based on the teams and meetups endpoints.

Displays number of meetups, speakers and contributors.

Animates on intersection.

Mobile:

Screenshot 2023-08-17 at 22 02 05

Desktop:

Screenshot 2023-08-17 at 22 02 34

Animation:

[screen-capture.webm](https://github.com/Front-End-Coders-Mauritius/frontendmu-astro/assets/88334281/39ad16cb-9c91-4cac-b609-a732415c36b5)

### CODE REVIEW

**Comment by houzyk** [comment]
please don't preview deploy yet. the build might fail

**Comment by houzyk** [comment]
So, it seems that calling an astro endpoint within an astro app itself requires SSR https://docs.astro.build/en/recipes/call-endpoints/. which makes sense tbh. that is why i think the build will probably fail. I'll investigate further and get back.

**Comment by MrSunshyne** [comment]
I think we should have a command/script that saves the output of the api routes on disk in json files. 
Those could then be easily imported within astro and used for stats. I'll think about it too and get back ! 

The gradient on the counter text looks very nice ! perhaps see if you can use the "verse" color scheme or the "--hue" css variable to build that gradient somehow, so that it still looks good when we use the theme switcher(paint bucket)

**Comment by houzyk** [comment]
Makes sense i think a script just before the build phase to fetch data from directus and store json on disk would work. wdy think?

**Comment by MrSunshyne** [comment]
@houzyk yep, I actually think we should use that script and download the stuff to disk and expose that, instead of using Astro endpoints. 

The build script would then become: 

from `npm run build`
to `npm run deploy`

where deploy is

```json
"scripts" : {
    "generate-api": "npm run ./scripts/generate-api.ts"
    "deploy" : "npm run generate-api && npm run build"
}
```

Or we could build a github action which only does this... lots of options here :sweat_smile:

**Comment by houzyk** [comment]
closing this PR for now as i implement the api response dump in order to avoid any redundant notifs or vercel trying to deploy

**Pull request closed without merging**
