### PR TITLE
Implement vercel cloud function to update the profile picture of user after sign up

### PR DESCRIPTION
**Pull request by MrSunshyne**
Pair programming session with @arwinneil 🎉

Procedure:
1. User logs in
2. Trigger cloud function fetchPicture using user authData.refreshToken securely
3. Cloud function gets google access token and require profile picture
4. Convert profile picture to base64
5. update user `profile_picture` field on directus with the base64 image

### CODE REVIEW

**Review by mahima98 — APPROVED** [review]

**Comment by arwinneil** [comment]
Toast is ugly

**Review by arwinneil — CHANGES_REQUESTED** [review]
Make the toast beautiful plz

**Comment by MrSunshyne** [comment]
@arwinneil toast has been beatifoolied

**Review by arwinneil — APPROVED** [review]
ezgif-2-2296ced862

**Pull request merged**
