### PR TITLE
[enhancement] ADD External Link Icon To Navbar

### PR DESCRIPTION
**Pull request by houzyk**
Added an outward link icon to any links in navbar that is external.

Better UX: user knows when they will be directed out of the site.

pics:

Screenshot 2023-08-04 at 20 05 49

### CODE REVIEW

**Comment by houzyk** [comment]
light mode pic:

Screenshot 2023-08-04 at 20 17 07

**Comment by MrSunshyne** [comment]
Thanks a lot for the PR @houzyk ! 

Could you use an icon from `unplugin-icon` instead of including an SVG file? We've recently added it as a dependency and it's working pretty well !

This should help :
1. Pick any icon from: https://icones.js.org/
2. Copy the name, e.g. `carbon:launch` for [external link](https://api.iconify.design/carbon:launch.svg)
3. Import is as such `import ExternalLinkIcon "~icons/carbon/launch"` 
4. Notice that we replace the `":"` with `"/"`
5. Profit !

**Comment by houzyk** [comment]
piccies

Screenshot 2023-08-04 at 21 36 26
Screenshot 2023-08-04 at 21 36 22

**Comment by MrSunshyne** [comment]
btw the `launch` icon was just a suggestion, you can pick any you think is nice. I'm merging this meanwhile. Thanks a lot!

**Comment by houzyk** [comment]
Oh yeah but i thought it looked cool 😂 nice choice

**Pull request merged**
